index/urls.py
from django.urls import path

from . import views

app_name = "index"

urlpatterns = [
    path('', views.index, name="index"),
]

plant_classification/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('index.urls')),
    path('admin/', admin.site.urls),
    path("cucumber_leaf_face/", include("cucumber_leaf_face.urls")),
    path("strawberry_leaf_face/", include("strawberry_leaf_face.urls")),
    path("eggplant_leaf_face/", include("eggplant_leaf_face.urls")),
    path("tomato_leaf_face/", include("tomato_leaf_face.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tomato_leaf_face/urls.py
from django.urls import path

from . import views

app_name = "tomato_leaf_face"

urlpatterns = [
    path("showall/", views.showall, name="showall"),
    path("upload/", views.upload, name="upload"),
    path("result/", views.result, name="result"),
]

tomato_leaf_face/models.py
from django.db import models

# Create your models here.

class Image(models.Model):
    picture = models.ImageField(upload_to="images/")
    title = models.CharField(max_length=200, default="picture")
    first_name = models.CharField(max_length=20, default="")
    second_name = models.CharField(max_length=20, default="")
    third_name = models.CharField(max_length=20, default="")
    fourth_name = models.CharField(max_length=20, default="")
    fifth_name = models.CharField(max_length=20, default="")
    first_value = models.FloatField(default=0)
    second_value = models.FloatField(default=0)
    third_value = models.FloatField(default=0)
    fourth_value = models.FloatField(default=0)
    fifth_value = models.FloatField(default=0)

    def __str__(self):
        return self.title

tomato_leaf_face/forms.py
from django import forms

from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["picture"]

tomato_leaf_face/views.py
from django.shortcuts import redirect, render

from .forms import ImageForm

# Create your views here.
from .models import Image
from .recognition.recognize import main

def showall(request):
    images = Image.objects.all().order_by("-pk")
    context = {"images": images}
    return render(request, "tomato_leaf_face/showall.html", context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img = Image.objects.get(pk=Image.objects.count())
            output = main(img.picture)
            img.first_name = output[0][0]
            img.first_value = output[0][1]
            img.second_name = output[1][0]
            img.second_value = output[1][1]
            img.third_name = output[2][0]
            img.third_value = output[2][1]
            img.fourth_name = output[3][0]
            img.fourth_value = output[3][1]
            img.fifth_name = output[4][0]
            img.fifth_value = output[4][1]
            img.save()
            return redirect("tomato_leaf_face:result")
    else:
        form = ImageForm()
    context = {"form": form}
    return render(request, "tomato_leaf_face/upload.html", context)

def result(request):
    images = Image.objects.all().order_by("-pk")
    context = {"images": images[1:], "now_image": images[0]}
    return render(request, "tomato_leaf_face/result.html", context)

tomato_leaf_face/templates/tomato_leaf_face/result.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>トマト病害識別器 | 識別結果</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'tomato_leaf_face/css/style.css' %}" />
    <link rel="shortcut icon" href="../../static/tomato_leaf_face/images/tomato-icon.ico">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.css" rel="stylesheet">
  </head>

  <body class="container">
    <h1>識別結果</h1>
    <div class="readable">
    <img src="{{ now_image.picture.url }}" width="360" class="mb-4" />
    <h2>これは{{ now_image.first_name }}の可能性が高いです</h2>
    <h1>詳細</h1>
    <h3>
      {{ now_image.first_name }} : 
      {{ now_image.first_value }}%
    </h3>
    <h3>
      {{ now_image.second_name }} :
      {{ now_image.second_value }}%
    </h3>
    <h3>
      {{ now_image.third_name }} :
      {{ now_image.third_value }}%
    </h3>
    <h3>
      {{ now_image.fourth_name }} :
      {{ now_image.fourth_value }}%
    </h3>
    <h3>
      {{ now_image.fifth_name }} :
      {{ now_image.fifth_value }}%
    </h3>
    </div>
    <h1>過去の結果</h1>
    <table class="result_table">
      <thead>
        <tr>
          <th>画像 \ 確率</th>
          <th>1st</th>
          <th>2nd</th>
          <th>3rd</th>
          <th>4th</th>
          <th>5th</th>
        </tr>
      </thead>
      <tbody class="result_history">
        {% for image in images %}
        <tr>
          <th class="history_img"><a href="{{ image.picture.url }}" data-lightbox="image" data-title="予測ラベル：{{ image.first_name }}"><img src="{{ image.picture.url }}" height="70" /></a></th>
          <td>
            <h3 class="name_value">
              {{ image.first_name }}<br />
              {{ image.first_value }}%
            </h3>
          </td>
          <td>
            <h3 class="name_value">
              {{ image.second_name }}<br />
              {{ image.second_value }}%
            </h3>
          </td>
          <td>
            <h3 class="name_value">
              {{ image.third_name }}<br />
              {{ image.third_value }}%
            </h3>
          </td>
          <td>
            <h3 class="name_value">
              {{ image.fourth_name }}<br />
              {{ image.fourth_value }}%
            </h3>
          </td>
          <td>
            <h3 class="name_value">
              {{ image.fifth_name }}<br />
              {{ image.fifth_value }}%
            </h3>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <div class="text-center upload_more mb-5">
      <a class="upload_more_button" href="{% url 'tomato_leaf_face:upload' %}">さらにアップロード</a>
    </div>
    <div class="text-center backtop mb-5">
      <a class="backtop_button" href="/">トップへ戻る</a>
    </div>
    <br />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" type="text/javascript"></script>
  </body>
</html>

tomato_leaf_face/templates/tomato_leaf_face/showall.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>トマト病害識別器 | 結果一覧</title>
    <link rel="stylesheet" type="text/css" href="{% static 'tomato_leaf_face/css/style.css' %}" />
    <link rel="shortcut icon" href="../../static/tomato_leaf_face/images/tomato-icon.ico">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.css" rel="stylesheet">
  </head>

  <body class="container">
    <h1>過去の結果一覧</h1>
    <table class="showall">
      <thead>
        <tr>
          <th>画像 \ 確率</th>
          <th>1st</th>
          <th>2nd</th>
          <th>3rd</th>
          <th>4th</th>
          <th>5th</th>
        </tr>
      </thead>
      <tbody class="showall_nama_value">
        {% for image in images %}
        <tr>
          <th><a href="{{ image.picture.url }}" data-lightbox="image" data-title="予測ラベル：{{ image.first_name }}"><img src="{{ image.picture.url }}" height="70" /></a></th>
          <td>
            <h3>
              {{ image.first_name }}<br />
              {{ image.first_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.second_name }}<br />
              {{ image.second_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.third_name }}<br />
              {{ image.third_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fourth_name }}<br />
              {{ image.fourth_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fifth_name }}<br />
              {{ image.fifth_value }}%
            </h3>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <br />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" type="text/javascript"></script>
  </body>
</html>

tomato_leaf_face/templates/tomato_leaf_face/upload.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>トマト病害識別器</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'tomato_leaf_face/css/style.css' %}" />
    <link rel="shortcut icon" href="../../static/tomato_leaf_face/images/tomato-icon.ico">
  </head>

  <body class="container">
    <h1>植物病害判定</h1>
    <div class="readable">
    <p class="h5">
      トマトの葉表に発生する病害種を識別するアプリです。
      <br />
      識別したいトマトの葉表画像をアップロードしてみましょう。
    </p>
    <h2 class="target">トマト対象病害</h2>
    <table class="diagnosis__labels__table">

      <tbody><tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">健全</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">うどんこ病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">灰色かび病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">すすかび病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">葉かび病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">疫病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">褐色輪紋病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">青枯病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">かいよう病</td>
      </tr>
      
      <tr class="diagnosis__labels__row">
      <td class="diagnosis__labels__label">黄化葉巻病</td>
      </tr>

      </tbody></table>
    <form
      enctype="multipart/form-data"
      action="{% url 'tomato_leaf_face:upload' %}"
      method="POST"
      class="form-block"
    >
      {% csrf_token %} {{form.as_p}}
      <br />
      <button class="submit_button" type="submit">アップロード</button>
      <a href="{% url 'tomato_leaf_face:showall' %}" class="past_results">過去の結果一覧を見る</a>
    </form>
    </div>
  </body>
</html>